### ISSUE TITLE
"Send invoice" screen

### ISSUE THREAD

**Issue by DebJanson** [default-settings/invoicr#33]
It would be good to be able to save the "send invoice" page halfway through - e.g. if you start writing a big email and then realise you need to check the invoice, you have to discard and go back to the invoice and the email content can't be saved (I currently have to copy and paste elsewhere)

It would also be good to be able to save the email content to a template?

**Comment by harryspink** [comment]
Hi Deb

For the first part of the issue we agree it's annoying but the solution would be to open a new tab.

We have however built and deployed the email templates feature you suggested. You can set your own templates by going to your preferences where you manage your default email template and clicking the 'Manage custom templates' button below.

I hope this helps :)
